/** @type {import('prettier').Config} */
export default {
  semi: true,
  trailingComma: 'all',
  singleQuote: true,
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'avoid',
  endOfLine: 'lf',
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  importOrder: [
    '^react',
    '^react-dom',
    '^@radix-ui',
    '^@/components/ui',
    '^@/components',
    '^@/lib',
    '^@/hooks',
    '^@/types',
    '^@/features',
    '^@/pages',
    '^@/utils',
    '^@',
    '^\\..',
    '^\\.',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderCaseInsensitive: true,
};